# Based on: https://github.com/vitejs/vite/blob/171e856e011512098591234d0557804c6175b625/.github/ISSUE_TEMPLATE/bug_report.yml
name: "\U0001F41E Bug report"
description: Report an issue
labels: ['Type: Bug']
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: 'Please provide a link via [eslint-interactive''s playground](https://stackblitz.com/edit/eslint-interactive-playground?file=src%2Findex.ts&view=editor) or a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required ([Why?](https://antfu.me/posts/why-reproductions-are-required)). If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "Status: Need More Info" label. If no duplicate is provided, the issue may be closed.'
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. E.g. if the issue only reproduces when eslint-interactive is installed locally or globally, please clarify which installation causes the issue.
      placeholder: Run `npm install` followed by `npx eslint-interactive .`
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{eslint,eslint-interactive,jiti}' --npmGlobalPackages '{eslint,eslint-interactive,jiti}' --binaries`
      render: shell
      placeholder: System, Binaries, npmPackages, npmGlobalPackages
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.

        1. Run `npx eslint-interactive ...`
        2. Provide the error log here in the format below.

        ````
        <details>
        <summary>Click to expand!</summary>

        ```shell
        // paste the log text here
        ```
        </details>
        ````
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/mizdra/eslint-interactive/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Make sure this is a eslint-interactive issue and not a eslint or eslint's plugin issue. For example, if it's a ESLint related bug, it should likely be reported to [eslint/eslint](https://github.com/eslint/eslint) instead.
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
