# Setup

## `npm install -g ../../` will not install dependencies, so install tarball generated by `npm pack`.
npm pack ../../
npm install -g $(ls mizdra-eslint-interactive-*.tgz)

## install peerDeps manually
npm install -g eslint@$(cat ../../node_modules/eslint/package.json | jq -r .version)


# Test cases

## Successful launch
eslint-interactive --version

## Successful lint without error
eslint-interactive pass.js

## can print error with eslint-formatter-codeframe
node can-print-error-with-eslint-formatter-codeframe.test.js
