name: benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          # Fix the version to stabilize results.
          node-version: 16.14.0
          cache: 'pnpm'

      - run: pnpm install

      - name: pnpm run build
        run: pnpm run build

      - name: Install valgrind
        run: sudo apt install -y valgrind

      - name: Setup cachegrind-benchmarking
        run: node benchmark/setup-cachegrind-benchmarking.js

      - name: Run cachegrind-benchmarking
        run: |
          RESULT=$( \
            python3 \
              third-party/cachegrind-benchmarking/cachegrind.py \
              node \
                --random-gc-interval=0 \
                --no-randomize-all-allocations \
                --hash-seed=0 \
                --random-seed=0 \
                --fuzzer-random-seed=0 \
                --no-turbo-stress-instruction-scheduling \
                --no-stress-compaction-random \
                --predictable \
                --predictable-gc-schedule \
                benchmark/run-cachegrind-benchmarking.js \
          )
          echo \{\"name\": \"cachegrind-benchmarking\", \"unit\": \"instructions\", \"value\": $RESULT \} >> benchmark/result.jsonl

      - name: Convert jsonl to json
        run: jq -s '.' benchmark/result.jsonl > benchmark/result.json

      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: benchmark/result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: '800%'
          # for test
          comment-always: true
